In [ ]:
#DATA preprocessing

#Imputation
"""Imputation is simply the process of substituting the missing values of our dataset.We can do this by defining our own customised function or we can simply perform imputation by using the Imputer class provided by sklearn."""

In [ ]:
from sklearn.preprocessing import imputation
imputer = imputation(missing_values='NaN' ,strategy='mean')
imputer = imputer.fit(df[['C','D']])
df[['C','D']] = imputer.transform(df[['C','D']])

In [ ]:
#Standardization

"""It is another integral preprocessing step.In Standardization we transform our values such that the mean of the values is 0 and the standard deviation is 1."""
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train = std.fit_transform(X_train)
X_test = std.transform(X_test)

In [2]:
#Mean removal

"""It involves removing the mean from each feature so that it is centered on zero. Mean removal helps in removing any bias from the features."""
import numpy as np

input_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, -4.3]])
from sklearn import preprocessing

datas = preprocessing.scale(input_data)
print(datas.mean(axis=0))
print(datas.std(axis=0))

[ 5.55111512e-17 -3.70074342e-17  0.00000000e+00 -1.85037171e-17]
[1. 1. 1. 1.]


In [4]:
#Scaling
"""The values of every feature in a data point can vary between random values. So, it is important to scale them so that this matches specified rules."""
data_scal = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled = data_scal.fit_transform(input_data)
data_scaled

array([[1.        , 0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.27118644, 1.        ],
       [0.33333333, 0.84444444, 0.        , 0.2       ]])

In [7]:
#Normalization

"""Normalization involves adjusting the values in the feature vector so as to measure them on a common scale. Here, the values of a feature vector are adjusted so that they sum up to 1."""
dat_normalize = preprocessing.normalize(input_data, norm='l1')
dat_normalize

array([[ 0.21582734, -0.10791367,  0.21582734, -0.46043165],
       [ 0.        ,  0.35714286, -0.1547619 ,  0.48809524],
       [ 0.0952381 ,  0.21904762, -0.27619048, -0.40952381]])

In [8]:
#Binarization

"""Binarization is used to convert a numerical feature vector into a Boolean vector."""
data_binar = preprocessing.Binarizer(threshold=1.4)
data_binrzd = data_binar.transform(input_data)
data_binrzd

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 0.]])

In [9]:
#One Hot Encoding

"""It may be required to deal with numerical values that are few and scattered, and you may not need to store these values."""
encoder = preprocessing.OneHotEncoder()
encoder.fit([  [0, 2, 1, 12], 
               [1, 3, 5, 3], 
               [2, 3, 2, 12], 
               [1, 2, 4, 3]
])
encoded_vector = encoder.transform([[2, 3, 5, 3]]).toarray()
print( "\nEncoded vector =", encoded_vector)


Encoded vector = [[0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]


C:\Users\USER\Anaconda3\envs\intuitive-deep-learning\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [20]:
#Label Encoding

"""we mostly come across a variety of labels which can be in the form of numbers or words."""

label_encoder = preprocessing.LabelEncoder()
input_classes = ['suzuki', 'ford', 'suzuki', 'toyota', 'ford', 'bmw']
label_encoder.fit(input_classes)
for i, item in enumerate(label_encoder.classes_):
    print (item, '-->', i)


bmw --> 0
ford --> 1
suzuki --> 2
toyota --> 3


In [ ]:
#linear regresion
from sklearn.linear_model import LinearRegression

#error
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_squared_log_error, median_absolute_error

#train_test_split
from sklearn.model_selection import train_test_split

#datasets
from sklearn import datasets

#logistic regression
from sklearn.linear_model importrt LogisticRegression

#classification report
from sklearn.metrics import classification_report

#confusion_matrix
from sklearn.metrics import confusion_matrix

#Decission tree clasifir and regressor
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor

#random forest
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor,RandomTreesEmbedding

#naive_bayes
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB,

#KNN
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor

#SVM 
from sklearn.svm import SVC,SVR

#un-supervised learning
#k-means clustering
from sklearn.cluster import KMeans

#PCA
from sklearn.decomposition import PCA